### PR TITLE
fix(components): Use own `flattenChildren` helper to fix ESM build

### LINKED ISSUE #1796: `react-keyed-flatten-children` breaks ESM build
## Description

`react-keyed-flatten-children` does not work with ESM, see issue https://github.com/grrowl/react-keyed-flatten-children/issues/3

## How to reproduce

1. Create an app with CRA
2. Use `<Stack>`
3. ErrrRRRrrrrrrr

## Expected behavior

Well, this should work!

## Screenshots

```
Uncaught TypeError: react_keyed_flatten_children__WEBPACK_IMPORTED_MODULE_1__ is not a function
The above error occurred in the <Columns> component:
Columns@http://localhost:3000/static/js/bundle.js:65046:7
ConfigGenerator@http://localhost:3000/static/js/bundle.js:644:71
PrivateRoute@http://localhost:3000/static/js/bundle.js:1368:7
Routes@http://localhost:3000/static/js/bundle.js:55108:7
Router@http://localhost:3000/static/js/bundle.js:55045:7
BrowserRouter@http://localhost:3000/static/js/bundle.js:54522:7
AppRouter@http://localhost:3000/static/js/bundle.js:1232:71
KeycloakProvider@http://localhost:3000/static/js/bundle.js:16084:47
App@http://localhost:3000/static/js/bundle.js:82:69
div
$7b14dc4b86354e5c$var$OverlayContainerDOM@http://localhost:3000/static/js/bundle.js:13314:7
$7b14dc4b86354e5c$export$178405afcd8c5eb@http://localhost:3000/static/js/bundle.js:13275:7
$7b14dc4b86354e5c$export$bf688221f59024e5
ThemeProvider@http://localhost:3000/static/js/bundle.js:2208:64
ThemeProvider@http://localhost:3000/static/js/bundle.js:68357:7
MarigoldProvider@http://localhost:3000/static/js/bundle.js:65474:7
```

### PR DESCRIPTION
**Pull request by sebald**
Closes #1796

### CODE REVIEW

File: packages/components/src/utils/flatten-children.ts [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+): ReactChild[] =>
+  Children.toArray(children).reduce((acc: ReactChild[], node) => {
+    if (isFragment(node)) {
+      acc.push.apply(
+        acc,
+        flattenChildren(
+          node.props.children,
+          depth + 1,
+          /**
+           * No need for index fallback, Eeact will always assign keys
```
Comment (ti10le) [inline packages/components/src/utils/flatten-children.ts:32]: *React

**Review by ti10le — APPROVED** [review]

File: packages/components/src/utils/flatten-children.ts [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+ * array while ensuring element and fragment keys are preserved, unique, and stable between renders.
+ *
+ * Copied from https://github.com/grrowl/react-keyed-flatten-children (since ESM import doesn't work with the module)
+ */
+export const flattenChildren = (
+  children: ReactNode,
+  depth: number = 0,
+  keys: (string | number)[] = []
+): ReactChild[] =>
+  Children.toArray(children).reduce((acc: ReactChild[], node) => {
```
Comment (ti10le) [inline packages/components/src/utils/flatten-children.ts:24]: why ReactChild[] is called acc?

**Review by ti10le — DISMISSED** [review]

File: .changeset/poor-gifts-hug.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@marigold/components": patch
```
[the remark this answers is not in the document]
Comment (sebald) [reply .changeset/poor-gifts-hug.md:2]: bugfix = patch

File: packages/components/src/utils/flatten-children.ts (hunk 2 above)
Comment (sebald) [reply packages/components/src/utils/flatten-children.ts:24]: I copied the code ... `acc` is short for `accumulator` this is what the first argument of `.reduce` is called if you look at the signature. This is the thing that is passed to every callback and returned as a result of the reduce.

Comment (sebald) [reply packages/components/src/utils/flatten-children.ts:24]: I was really tempted to not use reduce here because it usually makes the code harder to read ...

File: .changeset/poor-gifts-hug.md (hunk 3 above)
[the remark this answers is not in the document]
Comment (ti10le) [reply .changeset/poor-gifts-hug.md:2]: Oh ok yes ok it is to fix a bug. I thought its minor because of the new own flattenChildren.

**Review by ti10le — APPROVED** [review]
