### PR TITLE
docs: fix responsive layout and table

### LINKED ISSUE #2377: fix mobile navigation

### PR DESCRIPTION
**Pull request by sarahgm**
closes #2377

### CODE REVIEW

File: docs/src/components/FigmaLink.tsx [hunk 1]
```diff
@@ -8,7 +8,8 @@ export const FigmaLink = ({ href }: { href: URL }) => (
       borderColor: 'background.light',
       borderRadius: '10px',
       textAlign: 'center',
-      justifySelf: 'end',
+      width: 'max-content',
+      ml: 'auto',
```
Comment (benediktgrether) [inline docs/src/components/FigmaLink.tsx:12]: i think we should position the figma link button on the left side on mobile devices and change in line 15 `mt: -2rem`. to `mt: -1rem`

**Review by benediktgrether — APPROVED** [review]
